// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yes.Data;

#nullable disable

namespace Yes.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Yes.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "R_001",
                            Title = "Manager"
                        },
                        new
                        {
                            Id = "R_002",
                            Title = "Receptionist"
                        },
                        new
                        {
                            Id = "R_003",
                            Title = "Staff"
                        });
                });

            modelBuilder.Entity("Yes.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Role_id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "U_001",
                            Description = "Hotel Manager",
                            Password = "$2a$11$dHB6CXy/IQe09Bncrvyrp.CAaBcmpw4u0N.0lNl7qspLjwNa7CV6a",
                            Role_id = "R_001",
                            Username = "Manager"
                        },
                        new
                        {
                            Id = "U_002",
                            Description = "Front Desk Receptionist",
                            Password = "$2a$11$PSG4fRx8q6RBM5elp3tYO.2ZriMV6CgEPmgvMcCK1.UUHhmtdx95e",
                            Role_id = "R_002",
                            Username = "Receptionist"
                        },
                        new
                        {
                            Id = "U_003",
                            Description = "Hotel Staff",
                            Password = "$2a$11$LROwwHR8HZYHGps41oPzMe7Mtn0hpTtHJlKCRHYwsNhgkffyVDaeW",
                            Role_id = "R_003",
                            Username = "Staff"
                        });
                });

            modelBuilder.Entity("Yes.Models.User", b =>
                {
                    b.HasOne("Yes.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("Role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Yes.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
