name: Build Docker Image for Server

on:
  push:
    branches:
      - main
      - build-*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate HTTPS Certificate
        run: |
          mkdir -p server/https
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
            -keyout server/https/aspnetcore-dev-key.pem \
            -out server/https/aspnetcore-dev-cert.pem \
            -subj "/CN=localhost"
          openssl pkcs12 -export \
            -out server/https/aspnetcore-dev-cert.pfx \
            -inkey server/https/aspnetcore-dev-key.pem \
            -in server/https/aspnetcore-dev-cert.pem \
            -password pass:password

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.SERVER_IMAGE_NAME }}:latest