name: Staging Frontend to Ducktrio ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Attach environment variables
        run: |
          echo '${{ secrets.FRONT_ENV }}' > frontend/.env

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image and push to ACR
        uses: docker/build-push-action@v5
        with:
          context: "./frontend"
          file: "./frontend/Dockerfile"
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.FRONTEND_IMAGE_NAME }}:staging
            ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.FRONTEND_IMAGE_NAME }}:${{ github.sha }}
