name: Staging Server to Ducktrio ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate HTTPS Certificate
        run: |
          mkdir -p server/https
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
            -keyout server/https/aspnetcore-dev-key.pem \
            -out server/https/aspnetcore-dev-cert.pem \
            -subj "/CN=localhost"
          openssl pkcs12 -export \
            -out server/https/aspnetcore-dev-cert.pfx \
            -inkey server/https/aspnetcore-dev-key.pem \
            -in server/https/aspnetcore-dev-cert.pem \
            -password pass:password

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image and push to ACR staging
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.SERVER_IMAGE_NAME }}:staging
            ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.SERVER_IMAGE_NAME }}:${{ github.sha }}
        